#!/usr/bin/python3
import sys
import time


def factorize(number):
    """
    Take a number
    Args:
        number: integer
        Return: A tuple of two factors if number is pair.
            None if the number is prime
    """
    for i in range(2, int((number**0.5) + 1)):
        if number % i == 0:
            return (i, number // i)
    return None


if __name__ == "__main__":

    """
    Read the number in file
    """
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    filename = sys.argv[1]

    try:
        with open(filename, 'r') as file:
            lines = file.readlines()
    except FileNotFoundError:
        print("Error: file not found")
        exit()

    start_time = time.time()
    """
    Loop over each line in the file which contains a natural number
    call factorize def for each number
    """
    for line in lines:
        try:
            number = int(line.strip())
        except ValueError:
            print("Error: Invalid input")
            continue
        factors = factorize(number)
        if factors:
            print("{:d}={:d}*{:d}".format(number, factors[0], factors[1]))

        """
        If excute of the program pass 5 seconds,
        the program exit with an error message
        """
        if time.time() - start_time > 5:
            print("Error: Time limit exceeded")
            exit()
print()
elapse_time = time.time() - start_time
print(f"Execution time: {elapse_time:.3f} seconds")
